=== ngphloc/zebra/runtime/wow/xmlroot/items/fileOfQuestions.dtd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Santi (Particular) -->
<!--DTD generated by XML Spy v4.2 U (http://www.xmlspy.com)-->
<!--Comment describing your root element-->
<!ELEMENT fileOfQuestions (concept, questions)>
<!ATTLIST fileOfQuestions
	fileName CDATA #REQUIRED
	name CDATA #REQUIRED
	course CDATA #REQUIRED
	path CDATA #REQUIRED
	numberOfAnswersForFile CDATA #REQUIRED
>
<!ELEMENT concept EMPTY>
<!ATTLIST concept
	value CDATA #REQUIRED
>
<!ELEMENT questions (question*)>
<!ELEMENT question (enunciate, image, answers, irtParameters, statisticParameters, testFiles?)>
<!ATTLIST question
	codeQuestion CDATA #REQUIRED
>
<!ELEMENT enunciate (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT answers (answer+)>
<!ATTLIST answers
	numberOfCorrect CDATA #REQUIRED
	numberOfAnswers CDATA #REQUIRED
>
<!ELEMENT irtParameters (difficulty, discrimination, guessing)>
<!ELEMENT statisticParameters (exhibitionRate, answerTime, successRate, numberOfUses, numberOfSuccesses)>
<!ELEMENT testFiles (classicTest?, adaptiveTest?)>
<!ELEMENT answer (textAnswer, correct, explanation)>
<!ATTLIST answer
	codeAnswer CDATA #REQUIRED
>
<!ELEMENT difficulty (#PCDATA)>
<!ELEMENT guessing (#PCDATA)>
<!ELEMENT discrimination (#PCDATA)>
<!ELEMENT exhibitionRate (#PCDATA)>
<!ELEMENT answerTime (#PCDATA)>
<!ELEMENT successRate (#PCDATA)>
<!ELEMENT numberOfUses (#PCDATA)>
<!ELEMENT numberOfSuccesses (#PCDATA)>
<!ELEMENT classicTest (classicTestFilePath*)>
<!ELEMENT adaptiveTest (adaptiveTestFilePath*)>
<!ELEMENT textAnswer (#PCDATA)>
<!ELEMENT correct (#PCDATA)>
<!ELEMENT explanation (#PCDATA)>
<!ELEMENT classicTestFilePath (#PCDATA)>
<!ELEMENT adaptiveTestFilePath (#PCDATA)>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/OperatorsTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="OperatorsTest_javatutorial_items.xml" name="OperatorsTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/OperatorsTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.OperatorsTest" /><questions><question codeQuestion="1"><enunciate>Consider the following code snippet: "arrayOfInts[j] &gt; arrayOfInts[j+1]". What operators does the code contain?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="4"><answer codeAnswer="1"><textAnswer>[], &gt;, +</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>[], &gt;, j</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>&gt;,+</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="4"><textAnswer>+, []</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.25</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/OperatorsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>Consider the following code snippet: "int i = 10; int n = i++%5;". What are the values of i and n after the code is executed?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="5"><answer codeAnswer="1"><textAnswer>i is 10, and n is 0</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>i is 11, and n is 1</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>i is 11, and n is 0</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="4"><textAnswer>i is 10, and n is 1</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="5"><textAnswer>i is 9, and n is 1</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.2</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/OperatorsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="3"><enunciate>Consider the following code snippet: "int i = 10; int n = i++%5;". What are the final values of i and n if instead of using the postfix increment operator (i++), you use the prefix version (++i))?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="4"><answer codeAnswer="1"><textAnswer>i is 11, and n is 1</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>i is 11, and n is 0</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>i is 10, and n is 1</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="4"><textAnswer>i is 12, and n is 0</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.25</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/OperatorsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="4"><enunciate>What is the value of i after the following code snippet executes: "int i = 8; i &gt;&gt;=2;"</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="4"><answer codeAnswer="1"><textAnswer>i is 4.</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>i is 2.</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>i is 0.</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="4"><textAnswer>i is 1.</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.25</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/OperatorsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="5"><enunciate>What is the value of i after the following code snippet executes: "int i = 17; i &gt;&gt;=1;"</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="4"><answer codeAnswer="1"><textAnswer>i is 8.</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>i is 16.</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>i is 7.</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="4"><textAnswer>i is 34.</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.25</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/OperatorsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/VariablesTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="VariablesTest_javatutorial_items.xml" name="VariablesTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/VariablesTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.VariablesTest" /><questions><question codeQuestion="1"><enunciate>Write here the text question.Which of the following are valid variable names?</enunciate><image /><answers numberOfCorrect="6" numberOfAnswers="10"><answer codeAnswer="1"><textAnswer>int</textAnswer><correct>false</correct><explanation>"int" is the keyword</explanation></answer><answer codeAnswer="2"><textAnswer>anInt</textAnswer><correct>true</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>i</textAnswer><correct>true</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="4"><textAnswer>i1</textAnswer><correct>true</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="5"><textAnswer>1</textAnswer><correct>false</correct><explanation>This is a number letter</explanation></answer><answer codeAnswer="6"><textAnswer>thing1</textAnswer><correct>true</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="7"><textAnswer>1thing</textAnswer><correct>false</correct><explanation>The first letter can't be a number letter</explanation></answer><answer codeAnswer="8"><textAnswer>ONE-HUNDRED</textAnswer><correct>false</correct><explanation>The minus letter "-" is the special world not allowed in variable name</explanation></answer><answer codeAnswer="9"><textAnswer>ONE_HUNDRED</textAnswer><correct>true</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="10"><textAnswer>something2do</textAnswer><correct>true</correct><explanation>No explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.1</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/VariablesTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>Given the source code of program (see the following), what is the name of each variable declared in the program? (Remember that method parameters are also variables) And What is the scope of each variable?</enunciate><image>javatutorial/itemsFiles/images/VariablesTest_javatutorial_items/VariablesTest_javatutorial_items_2.gif</image><answers numberOfCorrect="1" numberOfAnswers="3"><answer codeAnswer="1"><textAnswer>Names of Variables are: args, sum, current.The variable "args" has scope within the entire main method. The variable "sum" is a local variable that is valid from its declaration to the end of the main method. The variable "current" is available from its declaration to the } that closes the for loop</textAnswer><correct>true</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>Names of Variables are: args, Sum, current. The variable "args" has scope within the entire main method. The variable "Sum" is a global variable. The variable "current" is available from its declaration to the } that closes the for loop</textAnswer><correct>false</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>Names of Variables are: args, current, sum. The variable "args" is a global variable. The variable "current" is available from its declaration to the } that closes the for loop. The variable "sum" has scope within the entire main method.</textAnswer><correct>false</correct><explanation>No explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.3333333333333333</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/VariablesTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/StringsTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="StringsTest_javatutorial_items.xml" name="StringsTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/StringsTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.StringsTest" /><questions><question codeQuestion="1"><enunciate>What is the initial capacity of the following string buffer?</enunciate><image>javatutorial/itemsFiles/images/StringsTest_javatutorial_items/StringsTest_javatutorial_items_1.gif</image><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>It's the length of the initial string + 16: 26 + 16 = 42.</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>26.</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/StringsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>What is the value displayed by the expression hannah.length()?</enunciate><image>javatutorial/itemsFiles/images/StringsTest_javatutorial_items/StringsTest_javatutorial_items_2.gif</image><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>32</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>31</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/StringsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="3"><enunciate>How long is the string returned by the following expression? What is the string?</enunciate><image>javatutorial/itemsFiles/images/StringsTest_javatutorial_items/StringsTest_javatutorial_items_3.gif</image><answers numberOfCorrect="1" numberOfAnswers="3"><answer codeAnswer="1"><textAnswer>It's 3 characters in length: car</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>It's 3 characters in length: saw</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>It's 3 characters in length: cat</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.3333333333333333</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/StringsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/NestedClassesTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="NestedClassesTest_javatutorial_items.xml" name="NestedClassesTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/NestedClassesTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.NestedClassesTest" /><questions><question codeQuestion="1"><enunciate>Match each situation in the first column with the most appropriate type of nested class in the second column.</enunciate><image>javatutorial/itemsFiles/images/NestedClassesTest_javatutorial_items/NestedClassesTest_javatutorial_items_1.gif</image><answers numberOfCorrect="6" numberOfAnswers="10"><answer codeAnswer="1"><textAnswer>a. 2. (protected inner class)</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>b. 3. (public static nested class)</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>c. 6. (private inner class)</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="4"><textAnswer>d. 1. (anonymous inner class)</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="5"><textAnswer>e. 4. (protected static nested class)</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="6"><textAnswer>f. 5. (private static nested class)</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="7"><textAnswer>c. 3. (private inner class)</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="8"><textAnswer>d. 2. (anonymous inner class)</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="9"><textAnswer>f. 1. (private static nested class)</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="10"><textAnswer>b. 6. (public static nested class)</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.1</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/NestedClassesTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/GenericsTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="GenericsTest_javatutorial_items.xml" name="GenericsTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/GenericsTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.GenericsTest" /><questions><question codeQuestion="1"><enunciate>Is the following statement wrong or right: List&lt;Object&gt; list = new ArrayList&lt;?&gt;();</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>wrong</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>right</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/GenericsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>
