=== ngphloc/zebra/runtime/wow/xmlroot/items/fileOfQuestions.dtd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Santi (Particular) -->
<!--DTD generated by XML Spy v4.2 U (http://www.xmlspy.com)-->
<!--Comment describing your root element-->
<!ELEMENT fileOfQuestions (concept, questions)>
<!ATTLIST fileOfQuestions
	fileName CDATA #REQUIRED
	name CDATA #REQUIRED
	course CDATA #REQUIRED
	path CDATA #REQUIRED
	numberOfAnswersForFile CDATA #REQUIRED
>
<!ELEMENT concept EMPTY>
<!ATTLIST concept
	value CDATA #REQUIRED
>
<!ELEMENT questions (question*)>
<!ELEMENT question (enunciate, image, answers, irtParameters, statisticParameters, testFiles?)>
<!ATTLIST question
	codeQuestion CDATA #REQUIRED
>
<!ELEMENT enunciate (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT answers (answer+)>
<!ATTLIST answers
	numberOfCorrect CDATA #REQUIRED
	numberOfAnswers CDATA #REQUIRED
>
<!ELEMENT irtParameters (difficulty, discrimination, guessing)>
<!ELEMENT statisticParameters (exhibitionRate, answerTime, successRate, numberOfUses, numberOfSuccesses)>
<!ELEMENT testFiles (classicTest?, adaptiveTest?)>
<!ELEMENT answer (textAnswer, correct, explanation)>
<!ATTLIST answer
	codeAnswer CDATA #REQUIRED
>
<!ELEMENT difficulty (#PCDATA)>
<!ELEMENT guessing (#PCDATA)>
<!ELEMENT discrimination (#PCDATA)>
<!ELEMENT exhibitionRate (#PCDATA)>
<!ELEMENT answerTime (#PCDATA)>
<!ELEMENT successRate (#PCDATA)>
<!ELEMENT numberOfUses (#PCDATA)>
<!ELEMENT numberOfSuccesses (#PCDATA)>
<!ELEMENT classicTest (classicTestFilePath*)>
<!ELEMENT adaptiveTest (adaptiveTestFilePath*)>
<!ELEMENT textAnswer (#PCDATA)>
<!ELEMENT correct (#PCDATA)>
<!ELEMENT explanation (#PCDATA)>
<!ELEMENT classicTestFilePath (#PCDATA)>
<!ELEMENT adaptiveTestFilePath (#PCDATA)>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/CreatingClassesTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="CreatingClassesTest_javatutorial_items.xml" name="CreatingClassesTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/CreatingClassesTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.CreatingClassesTest" /><questions><question codeQuestion="1"><enunciate>How many class variables does the IdentifyMyParts class contain? What are their names?</enunciate><image>javatutorial/itemsFiles/images/CreatingClassesTest_javatutorial_items/CreatingClassesTest_javatutorial_items_1.gif</image><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>1, x</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>7, y</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/CreatingClassesTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>How many instance variables does the IdentifyMyParts class contain? What are their names?</enunciate><image>javatutorial/itemsFiles/images/CreatingClassesTest_javatutorial_items/CreatingClassesTest_javatutorial_items_2.gif</image><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>1,x</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>1, y</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/CreatingClassesTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/GettingStartedTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="GettingStartedTest_javatutorial_items.xml" name="GettingStartedTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/GettingStartedTest_javatutorial_items.xml" numberOfAnswersForFile="4"><concept value="javatutorial.GettingStartedTest" /><questions><question codeQuestion="1"><enunciate>When you compile a program written in the Java programming language, the compiler converts the human-readable source file into platform-independent code that a Java Virtual Machine can understand. What is this platform-independent code called?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="4"><answer codeAnswer="1"><textAnswer>Excutable code</textAnswer><correct>false</correct><explanation>No explanation</explanation></answer><answer codeAnswer="2"><textAnswer>Byte code</textAnswer><correct>true</correct><explanation>No explanation</explanation></answer><answer codeAnswer="3"><textAnswer>Interpret code</textAnswer><correct>false</correct><explanation>No explanation</explanation></answer><answer codeAnswer="4"><textAnswer>Shell code</textAnswer><correct>false</correct><explanation>No explanation</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.25</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><classicTest><classicTestFilePath>javatutorial/test/GettingStartedTest_javatutorial_C_activity.xml</classicTestFilePath></classicTest><adaptiveTest><adaptiveTestFilePath>javatutorial/test/GettingStartedTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>Which of the following is not a valid comment:</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="4"><answer codeAnswer="1"><textAnswer>/** comment */</textAnswer><correct>false</correct><explanation>No explanation</explanation></answer><answer codeAnswer="2"><textAnswer>/* comment */</textAnswer><correct>false</correct><explanation>No explanation</explanation></answer><answer codeAnswer="3"><textAnswer>/* comment</textAnswer><correct>true</correct><explanation>No explanation</explanation></answer><answer codeAnswer="4"><textAnswer>// comment</textAnswer><correct>false</correct><explanation>No explanation</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.25</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><classicTest><classicTestFilePath>javatutorial/test/GettingStartedTest_javatutorial_C_activity.xml</classicTestFilePath></classicTest><adaptiveTest><adaptiveTestFilePath>javatutorial/test/GettingStartedTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="3"><enunciate>What is the first thing you should check if the interpreter returns the error: Exception in thread "main" java.lang.NoClassDefFoundError: HelloWorldApp.java</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="4"><answer codeAnswer="1"><textAnswer>Check runtime errors in HelloWorldApp.java code</textAnswer><correct>false</correct><explanation>No explanation</explanation></answer><answer codeAnswer="2"><textAnswer>Check where Java Runtime Environment is installed</textAnswer><correct>false</correct><explanation>No explanation</explanation></answer><answer codeAnswer="3"><textAnswer>Check your classpath. The interpreter cannot find your class</textAnswer><correct>true</correct><explanation>No explanation</explanation></answer><answer codeAnswer="4"><textAnswer>Check Java interpreter</textAnswer><correct>false</correct><explanation>No explanation</explanation></answer></answers><irtParameters><difficulty>2.0</difficulty><discrimination>3.0</discrimination><guessing>0.25</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><classicTest><classicTestFilePath>javatutorial/test/GettingStartedTest_javatutorial_C_activity.xml</classicTestFilePath></classicTest><adaptiveTest><adaptiveTestFilePath>javatutorial/test/GettingStartedTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/NumbersTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="NumbersTest_javatutorial_items.xml" name="NumbersTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/NumbersTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.NumbersTest" /><questions><question codeQuestion="1"><enunciate>What Integer method can you use to convert an int into a string that expresses the number in hexadecimal? For example, what method converts the integer 65 into the string "41"?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="3"><answer codeAnswer="1"><textAnswer>toHexText</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>toHexString</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>hexString</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.3333333333333333</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/NumbersTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>What Double method can you use to detect whether a floating-point number has the special value Not a Number?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="3"><answer codeAnswer="1"><textAnswer>isNull</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>isNotNumber</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>isNaN</textAnswer><correct>true</correct><explanation>No Explanation</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.3333333333333333</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/NumbersTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="3"><enunciate>What is the value of the following expression, and why? new Integer(1).equals(new Long(1))</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="3"><answer codeAnswer="1"><textAnswer>False. The two objects (the Integer and the Long) have different types.</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>True. The two objects (the Integer and the Long) are number types.</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>False. There is no method "equals"</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.3333333333333333</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/NumbersTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/EnumeratedTypesTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="EnumeratedTypesTest_javatutorial_items.xml" name="EnumeratedTypesTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/EnumeratedTypesTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.EnumeratedTypesTest" /><questions><question codeQuestion="1"><enunciate>What are right assertions about enumerated types?</enunciate><image /><answers numberOfCorrect="3" numberOfAnswers="4"><answer codeAnswer="1"><textAnswer>They are typesafe.</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>They exist in their own namespace</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>They are Comparable and Serializable</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="4"><textAnswer>it's possible for one enum type to extend another enum type</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.25</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/EnumeratedTypesTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/ExpressionsStatementsBlocksTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="ExpressionsStatementsBlocksTest_javatutorial_items.xml" name="ExpressionsStatementsBlocksTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/ExpressionsStatementsBlocksTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.ExpressionsStatementsBlocksTest" /><questions><question codeQuestion="1"><enunciate>What are the data types of the following expressions, assuming that i's type is int?</enunciate><image>javatutorial/itemsFiles/images/ExpressionsStatementsBlocksTest_javatutorial_items/ExpressionsStatementsBlocksTest_javatutorial_items_1.gif</image><answers numberOfCorrect="1" numberOfAnswers="3"><answer codeAnswer="1"><textAnswer>Line 1: boolean. Line 2: int. Line3: int. Line 4: float. Line 5: boolean. Line 6: String</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>Line 1: boolean. Line 2: int. Line 3: int. Line 4: float. Line 5: int. Line 6: int</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>Line 1: int. Line 2: int. Line 3: int. Line 4: float. Line 5: boolean. Line 6: String</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.3333333333333333</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ExpressionsStatementsBlocksTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>Consider the following expression: "i--%5&gt;0". What is the result of the expression, assuming that the value of i is initially 10?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>false</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>true</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ExpressionsStatementsBlocksTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="3"><enunciate>Consider the following expression: "i--%5&gt;0". Modify the expression so that it has the same result but is easier for programmers to read.</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>i-- (% 5 &gt; 0)</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>(i-- % 5) &gt; 0</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ExpressionsStatementsBlocksTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/ManagingInheritanceTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="ManagingInheritanceTest_javatutorial_items.xml" name="ManagingInheritanceTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/ManagingInheritanceTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.ManagingInheritanceTest" /><questions><question codeQuestion="1"><enunciate>Consider the following two classes: ClassA, ClassB. Which method overrides a method in the superclass?</enunciate><image>javatutorial/itemsFiles/images/ManagingInheritanceTest_javatutorial_items/ManagingInheritanceTest_javatutorial_items_1.gif</image><answers numberOfCorrect="1" numberOfAnswers="3"><answer codeAnswer="1"><textAnswer>methodTwo</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>methodOne</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>methodFour</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.3333333333333333</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ManagingInheritanceTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>Consider the following two classes: ClassA, ClassB. Which method hides a method in the superclass?</enunciate><image>javatutorial/itemsFiles/images/ManagingInheritanceTest_javatutorial_items/ManagingInheritanceTest_javatutorial_items_2.gif</image><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>methodFour</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>methodTwo</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ManagingInheritanceTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/ArraysTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="ArraysTest_javatutorial_items.xml" name="ArraysTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/ArraysTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.ArraysTest" /><questions><question codeQuestion="1"><enunciate>What is the index of Brighton in the following array? String[] skiResorts = { "Whistler Blackcomb", "Squaw Valley", "Brighton", "Snowmass", "Sun Valley", "Taos" };</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>2</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>3</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ArraysTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>Given String[] skiResorts = { "Whistler Blackcomb", "Squaw Valley", "Brighton", "Snowmass", "Sun Valley", "Taos" }; What is the value of the expression skiResorts.length?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>6</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>8</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ArraysTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="3"><enunciate>Given: String[] skiResorts = { "Whistler Blackcomb", "Squaw Valley", "Brighton", "Snowmass", "Sun Valley", "Taos" }; What is the index of the last item in the array?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>5</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>4</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ArraysTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>
