=== ngphloc/zebra/runtime/wow/xmlroot/items/fileOfQuestions.dtd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Santi (Particular) -->
<!--DTD generated by XML Spy v4.2 U (http://www.xmlspy.com)-->
<!--Comment describing your root element-->
<!ELEMENT fileOfQuestions (concept, questions)>
<!ATTLIST fileOfQuestions
	fileName CDATA #REQUIRED
	name CDATA #REQUIRED
	course CDATA #REQUIRED
	path CDATA #REQUIRED
	numberOfAnswersForFile CDATA #REQUIRED
>
<!ELEMENT concept EMPTY>
<!ATTLIST concept
	value CDATA #REQUIRED
>
<!ELEMENT questions (question*)>
<!ELEMENT question (enunciate, image, answers, irtParameters, statisticParameters, testFiles?)>
<!ATTLIST question
	codeQuestion CDATA #REQUIRED
>
<!ELEMENT enunciate (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT answers (answer+)>
<!ATTLIST answers
	numberOfCorrect CDATA #REQUIRED
	numberOfAnswers CDATA #REQUIRED
>
<!ELEMENT irtParameters (difficulty, discrimination, guessing)>
<!ELEMENT statisticParameters (exhibitionRate, answerTime, successRate, numberOfUses, numberOfSuccesses)>
<!ELEMENT testFiles (classicTest?, adaptiveTest?)>
<!ELEMENT answer (textAnswer, correct, explanation)>
<!ATTLIST answer
	codeAnswer CDATA #REQUIRED
>
<!ELEMENT difficulty (#PCDATA)>
<!ELEMENT guessing (#PCDATA)>
<!ELEMENT discrimination (#PCDATA)>
<!ELEMENT exhibitionRate (#PCDATA)>
<!ELEMENT answerTime (#PCDATA)>
<!ELEMENT successRate (#PCDATA)>
<!ELEMENT numberOfUses (#PCDATA)>
<!ELEMENT numberOfSuccesses (#PCDATA)>
<!ELEMENT classicTest (classicTestFilePath*)>
<!ELEMENT adaptiveTest (adaptiveTestFilePath*)>
<!ELEMENT textAnswer (#PCDATA)>
<!ELEMENT correct (#PCDATA)>
<!ELEMENT explanation (#PCDATA)>
<!ELEMENT classicTestFilePath (#PCDATA)>
<!ELEMENT adaptiveTestFilePath (#PCDATA)>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/LifeCycleOfObjectTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="LifeCycleOfObjectTest_javatutorial_items.xml" name="LifeCycleOfObjectTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/LifeCycleOfObjectTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.LifeCycleOfObjectTest" /><questions><question codeQuestion="1"><enunciate>Question 1: What's wrong with the following program?</enunciate><image>javatutorial/itemsFiles/images/LifeCycleOfObjectTest_javatutorial_items/LifeCycleOfObjectTest_javatutorial_items_1.gif</image><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>The code never creates a Rectangle (in a .java source file) object</textAnswer><correct>true</correct><explanation>With this simple program, the compiler generates a warning. However, in a more realistic situation, myRect might be initialized to null in one place, say in a constructor, and used later</explanation></answer><answer codeAnswer="2"><textAnswer>The attributes "width" and "height" don't belong to class Rectangle</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/LifeCycleOfObjectTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>The following code creates one Point (in a .java source file) object and one Rectangle (in a .java source file) object. How many references to those objects exist after the code executes?</enunciate><image>javatutorial/itemsFiles/images/LifeCycleOfObjectTest_javatutorial_items/LifeCycleOfObjectTest_javatutorial_items_2.gif</image><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>Only one references to Rectangle object.</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>There is one reference to the Point object and one to the Rectangle object.</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/LifeCycleOfObjectTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="3"><enunciate>How does a program destroy an object that it creates?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>A program does not explicitly destroy objects. A program can set all references to an object to null so that the becomes eligible for garbage collection</textAnswer><correct>true</correct><explanation>No Explanation</explanation></answer><answer codeAnswer="2"><textAnswer>Using the operator delete</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/LifeCycleOfObjectTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/UsingPackagesTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="UsingPackagesTest_javatutorial_items.xml" name="UsingPackagesTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/UsingPackagesTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.UsingPackagesTest" /><questions><question codeQuestion="1"><enunciate>Assume that you have written some classes. Belatedly, you decide that they should be split into three packages, as listed in the table below. Furthermore, assume that the classes are currently in the default package (they have no package statements). What line of code will you need to add to each source file to put each class in the right package?</enunciate><image>javatutorial/itemsFiles/images/UsingPackagesTest_javatutorial_items/UsingPackagesTest_javatutorial_items_1.gif</image><answers numberOfCorrect="1" numberOfAnswers="3"><answer codeAnswer="1"><textAnswer>In Client.java add: package mygame.client; In Server.java add: package mygame.server;: In Utilities.java add: package mygame.shared;</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>In Client.java add: package mygame.client; In Server.java add: package mygame.server;: In Utilities.java add: package mygame.server;</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>In Client.java add: package mygame.client; In Server.java add: package mygame.server;: In Utilities.java add: package mygame.client;</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.3333333333333333</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/UsingPackagesTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/tutorial/itemsFiles/testtutorial_tutorial_items.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="testtutorial_tutorial_items.xml" name="testtutorial_tutorial_items" course="tutorial" path="tutorial/itemsFiles/testtutorial_tutorial_items.xml" numberOfAnswersForFile="4"><concept value="tutorial.testtutorial" /><questions><question codeQuestion="1"><enunciate>Which attribute types are possible in AHA!?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="5"><answer codeAnswer="1"><textAnswer>integer, boolean and string</textAnswer><correct>true</correct><explanation>The other types are good ideas for the future, but not currently supported.</explanation></answer><answer codeAnswer="2"><textAnswer>integer, date and string</textAnswer><correct>false</correct><explanation>Date is certainly a good idea for the future, but currently not supported. However, the type boolean is supported, as well as integer and string.</explanation></answer><answer codeAnswer="3"><textAnswer>integer, boolean, string and date</textAnswer><correct>false</correct><explanation>Date is certainly a good idea for the future, but currently not supported.</explanation></answer><answer codeAnswer="4"><textAnswer>integer, real, boolean and string</textAnswer><correct>false</correct><explanation>Real is certainly a good idea for the future, but currently not supported.</explanation></answer><answer codeAnswer="5"><textAnswer>integer, real, date, boolean and string</textAnswer><correct>false</correct><explanation>Date and real are certainly a good ideas for the future, but currently not supported.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.2</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><classicTest><classicTestFilePath>tutorial/test/testtutorial_tutorial_C_activity.xml</classicTestFilePath></classicTest></testFiles></question><question codeQuestion="2"><enunciate>Which type of adaptation rules does AHA! use?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>event-condition-action rules</textAnswer><correct>true</correct><explanation>Although the rules only contain a condition and action they are triggered by an event, usually a page access, and that is the reason they are called event-condition-action rules.</explanation></answer><answer codeAnswer="2"><textAnswer>condition-action rules</textAnswer><correct>false</correct><explanation>Although the rules only contain a condition and action they are triggered by an event, usually a page access, and that is the reason they are called event-condition-action rules.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><classicTest><classicTestFilePath>tutorial/test/testtutorial_tutorial_C_activity.xml</classicTestFilePath></classicTest></testFiles></question><question codeQuestion="3"><enunciate>Which of the following statements about AHA! are true? (There can be more than one true statement.)</enunciate><image /><answers numberOfCorrect="2" numberOfAnswers="6"><answer codeAnswer="1"><textAnswer>AHA! works on machines where the mySQL database is not installed.</textAnswer><correct>true</correct><explanation>The code for accessing mySQL is included in the Java SDK, so AHA! will not complain that mySQL is missing. But of course you cannot use the option to store the concepts and user models in a mySQL database when you do not have mySQL installed.</explanation></answer><answer codeAnswer="2"><textAnswer>In an AHA! application there can be links that are underlined while other links are not underlined.</textAnswer><correct>true</correct><explanation>In AHA! the "conditional" and "unconditional" links are not underlined, but links to pages that are unrelated to the application's concept structure are shown with or without underlining depending on your browser's settings.</explanation></answer><answer codeAnswer="3"><textAnswer>AHA! is completely free.</textAnswer><correct>true</correct><explanation>AHA! is distributed under the GNU license. This guarantees that it is available for free, and also that you get free access to the complete source code. Furthermore, AHA! only relies on tools that are available for free as well (and many also under a GNU license or a similar license).</explanation></answer><answer codeAnswer="4"><textAnswer>AHA! is primarily an educational system.</textAnswer><correct>false</correct><explanation>AHA! can be used for many different types of adaptive applications. The only educational feature it offers is the multiple-choice module and that is not yet fully developed. It does not come with an authoring tool for instance.</explanation></answer><answer codeAnswer="5"><textAnswer>AHA! works well with all browsers on all platforms.</textAnswer><correct>false</correct><explanation>Unfortunately there are browsers with bugs in their implementation of HTTP or their support for HTML. These are mostly older ones, but many of them are still in use. Netscape 4 works reasonably well, although there are surprises with some aspects of xhtml which Netscape 4 was not designed for. Netscape 6 and 7 work well. Internet Explorer has problems with almost all versions, but with the latest version there should be no problem if you do not visit any webpages before going to an AHA! site.</explanation></answer><answer codeAnswer="6"><textAnswer>AHA! 2.0 is backward compatible with AHA! 1.0.</textAnswer><correct>false</correct><explanation>The concept structure in AHA! 2.0 is completely different from 1.0, and this has an effect on the adaptation rules and the conditional inclusion of fragments. Porting an AHA! 1.0 application to 2.0 is fairly straightforward, but AHA! 2.0 offers a much richer concept structure, so it would be a shame to make a simple translation of a 1.0 application to 2.0 without taking advantage of the new possibilities.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.16666666666666666</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><classicTest><classicTestFilePath>tutorial/test/testtutorial_tutorial_C_activity.xml</classicTestFilePath></classicTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/ObjectOrientedProgrammingConceptsTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="ObjectOrientedProgrammingConceptsTest_javatutorial_items.xml" name="ObjectOrientedProgrammingConceptsTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/ObjectOrientedProgrammingConceptsTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.ObjectOrientedProgrammingConceptsTest" /><questions><question codeQuestion="1"><enunciate>We uses Color.BLACK to refer the black color. What other colors can you get by name like this?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>Color.black, Color.blue, Color.cyan, Color.darkGray, Color.gray, Color.green, Color.lightGray, Color.magenta, Color.orange, Color.pink, Color.white, and Color.yellow</textAnswer><correct>true</correct><explanation>No explanation</explanation></answer><answer codeAnswer="2"><textAnswer>Just only Color.BLACK and Color.WHITE</textAnswer><correct>false</correct><explanation>No explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ObjectOrientedProgrammingConceptsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>How would you create a Color object to represent purple? (Hint: Purple is made up of equal parts red and blue.)</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>There is no pre-defined purple color in class Color</textAnswer><correct>false</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>You specify them using the RGB (red-green-blue) color model. In RGB, purple is: 0.5, 0.0, 0.5</textAnswer><correct>true</correct><explanation>No explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ObjectOrientedProgrammingConceptsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="3"><enunciate>What Graphics method would you use to draw a filled square?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="4"><answer codeAnswer="1"><textAnswer>fillRect</textAnswer><correct>true</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>drawRect</textAnswer><correct>false</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>drawPolygon</textAnswer><correct>false</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="4"><textAnswer>draw3DRect</textAnswer><correct>false</correct><explanation>No explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.25</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ObjectOrientedProgrammingConceptsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="4"><enunciate>What Graphics method (s) would you use to draw text?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="4"><answer codeAnswer="1"><textAnswer>drawImage and drawOval</textAnswer><correct>false</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>drawBytes and drawChars</textAnswer><correct>true</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>drawString and drawText</textAnswer><correct>false</correct><explanation>No explanation.</explanation></answer><answer codeAnswer="4"><textAnswer>print and println</textAnswer><correct>false</correct><explanation>No explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.25</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ObjectOrientedProgrammingConceptsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/ControlFlowStatementsTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="ControlFlowStatementsTest_javatutorial_items.xml" name="ControlFlowStatementsTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/ControlFlowStatementsTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.ControlFlowStatementsTest" /><questions><question codeQuestion="1"><enunciate>What's wrong with the following code snippet: "if (i = 1) { /* do something */ }"</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>It should use == instead of =</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>Wrong position for {</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ControlFlowStatementsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>Consider the following code snippet. What output do you think the code will produce if aNumber is 3?</enunciate><image>javatutorial/itemsFiles/images/ControlFlowStatementsTest_javatutorial_items/ControlFlowStatementsTest_javatutorial_items_2.gif</image><answers numberOfCorrect="1" numberOfAnswers="3"><answer codeAnswer="1"><textAnswer>second string third string</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>first string third string</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="3"><textAnswer>second string first string</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.3333333333333333</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/ControlFlowStatementsTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/itemsFiles/UsingInterfacesTest_javatutorial_items.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE fileOfQuestions SYSTEM "../../fileOfQuestions.dtd">
<fileOfQuestions fileName="UsingInterfacesTest_javatutorial_items.xml" name="UsingInterfacesTest_javatutorial_items" course="javatutorial" path="javatutorial/itemsFiles/UsingInterfacesTest_javatutorial_items.xml" numberOfAnswersForFile="2"><concept value="javatutorial.UsingInterfacesTest" /><questions><question codeQuestion="1"><enunciate>What methods would a class that implements the java.util.Iterator interface have to implement?</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>next, hasNext, and remove</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>Only next method</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/UsingInterfacesTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="2"><enunciate>What is wrong with the following interface?</enunciate><image>javatutorial/itemsFiles/images/UsingInterfacesTest_javatutorial_items/UsingInterfacesTest_javatutorial_items_2.gif</image><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>It has a method implementation in it. It should just have a declaration.</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>It mustn't have the keyword "public"</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>-1</numberOfUses><numberOfSuccesses>-1</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/UsingInterfacesTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question><question codeQuestion="3"><enunciate>Is the following interface valid? public interface Marker { }</enunciate><image /><answers numberOfCorrect="1" numberOfAnswers="2"><answer codeAnswer="1"><textAnswer>Yes. Methods are not required</textAnswer><correct>true</correct><explanation>Write here the explanation.</explanation></answer><answer codeAnswer="2"><textAnswer>No. One or more methods must be declared in interface</textAnswer><correct>false</correct><explanation>Write here the explanation.</explanation></answer></answers><irtParameters><difficulty>0.0</difficulty><discrimination>1.0</discrimination><guessing>0.5</guessing></irtParameters><statisticParameters><exhibitionRate>0.0</exhibitionRate><answerTime>0</answerTime><successRate>0.0</successRate><numberOfUses>0</numberOfUses><numberOfSuccesses>0</numberOfSuccesses></statisticParameters><testFiles><adaptiveTest><adaptiveTestFilePath>javatutorial/test/UsingInterfacesTest_javatutorial_A_activity.xml</adaptiveTestFilePath></adaptiveTest></testFiles></question></questions></fileOfQuestions>
