=== ngphloc/zebra/runtime/wow/xmlroot/items/testFile.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT testFile (concepts, questions, parameters, students?)>
<!ATTLIST testFile
	totalQuestion CDATA #IMPLIED
	lastUse CDATA #REQUIRED
	fileName CDATA #REQUIRED
	name CDATA #REQUIRED
	course CDATA #REQUIRED
	type (activity | exam) #REQUIRED
	execution (classic | adaptive) #REQUIRED
	path CDATA #REQUIRED
	enable (true | false) #REQUIRED
>
<!ELEMENT concepts (concept+)>
<!ATTLIST concepts
	abstractConcept CDATA #IMPLIED
>
<!ELEMENT questions (questionsFile+)>
<!ATTLIST questions
	numberOfFiles CDATA #REQUIRED
>
<!ELEMENT parameters (runningParameters, irtParameters?)>
<!ELEMENT students (student*)>
<!ELEMENT concept EMPTY>
<!ATTLIST concept
	value CDATA #REQUIRED
>
<!ELEMENT questionsFile (question+)>
<!ATTLIST questionsFile
	numberOfQuestions CDATA #REQUIRED
	path CDATA #REQUIRED
	concept CDATA #REQUIRED
>
<!ELEMENT runningParameters (presentationParameters, htmlParameters, evaluationParameters)>
<!ELEMENT irtParameters (start, continuation, stop)>
<!ELEMENT student EMPTY>
<!ATTLIST student
	login CDATA #REQUIRED
	make CDATA #REQUIRED
	canRepeat (true | false) #REQUIRED
	score CDATA #REQUIRED
	finish (true | false) #REQUIRED
	theta CDATA #IMPLIED
	standardError CDATA #IMPLIED
>
<!ELEMENT question EMPTY>
<!ATTLIST question
	codeQuestion CDATA #REQUIRED
>
<!ELEMENT presentationParameters (showInitialInfo, questionsOrder, answersOrder, showQuestionCorrection, verbose, showCorrectAnswers, timeOfAnswer, repeatWithoutAnswer, showFinalInfo)>
<!ELEMENT htmlParameters (bgColor, background, titleColor)>
<!ELEMENT evaluationParameters (incorrectAnswer, withoutAnswer, knowledgePercentage)>
<!ELEMENT start EMPTY>
<!ATTLIST start
	initialProficiency CDATA #REQUIRED
>
<!ELEMENT continuation EMPTY>
<!ATTLIST continuation
	irtModel (1 | 2 | 3) #REQUIRED
>
<!ELEMENT stop EMPTY>
<!ATTLIST stop
	value (standardError | numberItemsAdministred) #REQUIRED
	standardError CDATA #IMPLIED
	numberItemsAdministred CDATA #IMPLIED
>
<!ELEMENT showInitialInfo EMPTY>
<!ATTLIST showInitialInfo
	value (true | false) #REQUIRED
>
<!ELEMENT questionsOrder EMPTY>
<!ATTLIST questionsOrder
	value (RANDOM | SEQUENTIAL) #REQUIRED
>
<!ELEMENT answersOrder EMPTY>
<!ATTLIST answersOrder
	value (RANDOM | SEQUENTIAL) #REQUIRED
>
<!ELEMENT showQuestionCorrection EMPTY>
<!ATTLIST showQuestionCorrection
	value (true | false) #REQUIRED
>
<!ELEMENT verbose EMPTY>
<!ATTLIST verbose
	value (true | false) #REQUIRED
>
<!ELEMENT showCorrectAnswers EMPTY>
<!ATTLIST showCorrectAnswers
	value (true | false) #REQUIRED
>
<!ELEMENT timeOfAnswer EMPTY>
<!ATTLIST timeOfAnswer
	value CDATA #REQUIRED
>
<!ELEMENT repeatWithoutAnswer EMPTY>
<!ATTLIST repeatWithoutAnswer
	value (true | false) #REQUIRED
>
<!ELEMENT showFinalInfo EMPTY>
<!ATTLIST showFinalInfo
	value (true | false) #REQUIRED
>
<!ELEMENT bgColor EMPTY>
<!ATTLIST bgColor
	value CDATA #REQUIRED
>
<!ELEMENT background EMPTY>
<!ATTLIST background
	value CDATA #REQUIRED
>
<!ELEMENT titleColor EMPTY>
<!ATTLIST titleColor
	value CDATA #REQUIRED
>
<!ELEMENT incorrectAnswer EMPTY>
<!ATTLIST incorrectAnswer
	value CDATA #REQUIRED
	penalize (true | false) #REQUIRED
>
<!ELEMENT withoutAnswer EMPTY>
<!ATTLIST withoutAnswer
	value CDATA #REQUIRED
	penalize (true | false) #REQUIRED
>
<!ELEMENT knowledgePercentage EMPTY>
<!ATTLIST knowledgePercentage
	value CDATA #REQUIRED
>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/test/ObjectOrientedProgrammingConceptsTest_javatutorial_A_activity.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE testFile SYSTEM "../../testFile.dtd">
<testFile totalQuestion="4" lastUse="8/10/2009" fileName="ObjectOrientedProgrammingConceptsTest_javatutorial_A_activity.xml" name="Test for Object-Oriented Programming Concepts" course="javatutorial" type="activity" execution="adaptive" path="javatutorial/test/ObjectOrientedProgrammingConceptsTest_javatutorial_A_activity.xml" enable="true"><concepts><concept value="javatutorial.ObjectOrientedProgrammingConceptsTest" /></concepts><questions numberOfFiles="1"><questionsFile numberOfQuestions="4" path="javatutorial/itemsFiles/ObjectOrientedProgrammingConceptsTest_javatutorial_items.xml" concept="javatutorial.ObjectOrientedProgrammingConceptsTest"><question codeQuestion="1" /><question codeQuestion="2" /><question codeQuestion="3" /><question codeQuestion="4" /></questionsFile></questions><parameters><runningParameters><presentationParameters><showInitialInfo value="true" /><questionsOrder value="RANDOM" /><answersOrder value="RANDOM" /><showQuestionCorrection value="false" /><verbose value="false" /><showCorrectAnswers value="false" /><timeOfAnswer value="60" /><repeatWithoutAnswer value="false" /><showFinalInfo value="true" /></presentationParameters><htmlParameters><bgColor value="#FFFFFF" /><background value="" /><titleColor value="#0000ff" /></htmlParameters><evaluationParameters><incorrectAnswer value="2" penalize="true" /><withoutAnswer value="0" penalize="false" /><knowledgePercentage value="100" /></evaluationParameters></runningParameters><irtParameters><start initialProficiency="0.5" /><continuation irtModel="3" /><stop value="standardError" standardError="0.33" /></irtParameters></parameters></testFile>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/test/UsingPackagesTest_javatutorial_A_activity.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE testFile SYSTEM "../../testFile.dtd">
<testFile totalQuestion="1" lastUse="0" fileName="UsingPackagesTest_javatutorial_A_activity.xml" name="Test for Using Packages" course="javatutorial" type="activity" execution="adaptive" path="javatutorial/test/UsingPackagesTest_javatutorial_A_activity.xml" enable="true"><concepts><concept value="javatutorial.UsingPackagesTest" /></concepts><questions numberOfFiles="1"><questionsFile numberOfQuestions="1" path="javatutorial/itemsFiles/UsingPackagesTest_javatutorial_items.xml" concept="javatutorial.UsingPackagesTest"><question codeQuestion="1" /></questionsFile></questions><parameters><runningParameters><presentationParameters><showInitialInfo value="true" /><questionsOrder value="RANDOM" /><answersOrder value="RANDOM" /><showQuestionCorrection value="false" /><verbose value="false" /><showCorrectAnswers value="false" /><timeOfAnswer value="60" /><repeatWithoutAnswer value="false" /><showFinalInfo value="true" /></presentationParameters><htmlParameters><bgColor value="#FFFFFF" /><background value="" /><titleColor value="#000000" /></htmlParameters><evaluationParameters><incorrectAnswer value="2" penalize="true" /><withoutAnswer value="0" penalize="false" /><knowledgePercentage value="100" /></evaluationParameters></runningParameters><irtParameters><start initialProficiency="0.5" /><continuation irtModel="3" /><stop value="standardError" standardError="0.33" /></irtParameters></parameters></testFile>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/test/ManagingInheritanceTest_javatutorial_A_activity.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE testFile SYSTEM "../../testFile.dtd">
<testFile totalQuestion="2" lastUse="0" fileName="ManagingInheritanceTest_javatutorial_A_activity.xml" name="Test for Managing Inheritance" course="javatutorial" type="activity" execution="adaptive" path="javatutorial/test/ManagingInheritanceTest_javatutorial_A_activity.xml" enable="true"><concepts><concept value="javatutorial.ManagingInheritanceTest" /></concepts><questions numberOfFiles="1"><questionsFile numberOfQuestions="2" path="javatutorial/itemsFiles/ManagingInheritanceTest_javatutorial_items.xml" concept="javatutorial.ManagingInheritanceTest"><question codeQuestion="1" /><question codeQuestion="2" /></questionsFile></questions><parameters><runningParameters><presentationParameters><showInitialInfo value="true" /><questionsOrder value="SEQUENTIAL" /><answersOrder value="SEQUENTIAL" /><showQuestionCorrection value="false" /><verbose value="false" /><showCorrectAnswers value="false" /><timeOfAnswer value="60" /><repeatWithoutAnswer value="false" /><showFinalInfo value="true" /></presentationParameters><htmlParameters><bgColor value="#FFFFFF" /><background value="" /><titleColor value="#000000" /></htmlParameters><evaluationParameters><incorrectAnswer value="2" penalize="true" /><withoutAnswer value="0" penalize="false" /><knowledgePercentage value="100" /></evaluationParameters></runningParameters><irtParameters><start initialProficiency="0.5" /><continuation irtModel="3" /><stop value="standardError" standardError="0.33" /></irtParameters></parameters></testFile>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/test/VariablesTest_javatutorial_A_activity.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE testFile SYSTEM "../../testFile.dtd">
<testFile totalQuestion="2" lastUse="12/10/2009" fileName="VariablesTest_javatutorial_A_activity.xml" name="Test for Variables" course="javatutorial" type="activity" execution="adaptive" path="javatutorial/test/VariablesTest_javatutorial_A_activity.xml" enable="true"><concepts><concept value="javatutorial.VariablesTest" /></concepts><questions numberOfFiles="1"><questionsFile numberOfQuestions="2" path="javatutorial/itemsFiles/VariablesTest_javatutorial_items.xml" concept="javatutorial.VariablesTest"><question codeQuestion="1" /><question codeQuestion="2" /></questionsFile></questions><parameters><runningParameters><presentationParameters><showInitialInfo value="true" /><questionsOrder value="RANDOM" /><answersOrder value="RANDOM" /><showQuestionCorrection value="false" /><verbose value="false" /><showCorrectAnswers value="false" /><timeOfAnswer value="180" /><repeatWithoutAnswer value="false" /><showFinalInfo value="true" /></presentationParameters><htmlParameters><bgColor value="#FFFFFF" /><background value="" /><titleColor value="#0000ff" /></htmlParameters><evaluationParameters><incorrectAnswer value="2" penalize="true" /><withoutAnswer value="0" penalize="false" /><knowledgePercentage value="100" /></evaluationParameters></runningParameters><irtParameters><start initialProficiency="0.5" /><continuation irtModel="3" /><stop value="standardError" standardError="0.33" /></irtParameters></parameters></testFile>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/test/GenericsTest_javatutorial_A_activity.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE testFile SYSTEM "../../testFile.dtd">
<testFile totalQuestion="1" lastUse="0" fileName="GenericsTest_javatutorial_A_activity.xml" name="Test for Generics" course="javatutorial" type="activity" execution="adaptive" path="javatutorial/test/GenericsTest_javatutorial_A_activity.xml" enable="true"><concepts><concept value="javatutorial.GenericsTest" /></concepts><questions numberOfFiles="1"><questionsFile numberOfQuestions="1" path="javatutorial/itemsFiles/GenericsTest_javatutorial_items.xml" concept="javatutorial.GenericsTest"><question codeQuestion="1" /></questionsFile></questions><parameters><runningParameters><presentationParameters><showInitialInfo value="true" /><questionsOrder value="RANDOM" /><answersOrder value="RANDOM" /><showQuestionCorrection value="false" /><verbose value="false" /><showCorrectAnswers value="false" /><timeOfAnswer value="60" /><repeatWithoutAnswer value="false" /><showFinalInfo value="true" /></presentationParameters><htmlParameters><bgColor value="#FFFFFF" /><background value="" /><titleColor value="#000000" /></htmlParameters><evaluationParameters><incorrectAnswer value="2" penalize="true" /><withoutAnswer value="0" penalize="false" /><knowledgePercentage value="100" /></evaluationParameters></runningParameters><irtParameters><start initialProficiency="0.5" /><continuation irtModel="3" /><stop value="standardError" standardError="0.33" /></irtParameters></parameters></testFile>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/test/OperatorsTest_javatutorial_A_activity.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE testFile SYSTEM "../../testFile.dtd">
<testFile totalQuestion="5" lastUse="12/10/2009" fileName="OperatorsTest_javatutorial_A_activity.xml" name="Test for Operators" course="javatutorial" type="activity" execution="adaptive" path="javatutorial/test/OperatorsTest_javatutorial_A_activity.xml" enable="true"><concepts><concept value="javatutorial.OperatorsTest" /></concepts><questions numberOfFiles="1"><questionsFile numberOfQuestions="5" path="javatutorial/itemsFiles/OperatorsTest_javatutorial_items.xml" concept="javatutorial.OperatorsTest"><question codeQuestion="1" /><question codeQuestion="2" /><question codeQuestion="3" /><question codeQuestion="4" /><question codeQuestion="5" /></questionsFile></questions><parameters><runningParameters><presentationParameters><showInitialInfo value="true" /><questionsOrder value="RANDOM" /><answersOrder value="RANDOM" /><showQuestionCorrection value="false" /><verbose value="false" /><showCorrectAnswers value="false" /><timeOfAnswer value="60" /><repeatWithoutAnswer value="false" /><showFinalInfo value="true" /></presentationParameters><htmlParameters><bgColor value="#FFFFFF" /><background value="" /><titleColor value="#000000" /></htmlParameters><evaluationParameters><incorrectAnswer value="2" penalize="true" /><withoutAnswer value="0" penalize="false" /><knowledgePercentage value="100" /></evaluationParameters></runningParameters><irtParameters><start initialProficiency="0.5" /><continuation irtModel="3" /><stop value="standardError" standardError="0.33" /></irtParameters></parameters></testFile>

=== ngphloc/zebra/runtime/wow/xmlroot/items/javatutorial/test/GettingStartedTest_javatutorial_A_activity.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE testFile SYSTEM "../../testFile.dtd">
<testFile totalQuestion="3" lastUse="12/10/2009" fileName="GettingStartedTest_javatutorial_A_activity.xml" name="Test for Getting Started" course="javatutorial" type="activity" execution="adaptive" path="javatutorial/test/GettingStartedTest_javatutorial_A_activity.xml" enable="true"><concepts><concept value="javatutorial.GettingStartedTest" /></concepts><questions numberOfFiles="1"><questionsFile numberOfQuestions="3" path="javatutorial/itemsFiles/GettingStartedTest_javatutorial_items.xml" concept="javatutorial.GettingStartedTest"><question codeQuestion="1" /><question codeQuestion="2" /><question codeQuestion="3" /></questionsFile></questions><parameters><runningParameters><presentationParameters><showInitialInfo value="true" /><questionsOrder value="RANDOM" /><answersOrder value="RANDOM" /><showQuestionCorrection value="false" /><verbose value="true" /><showCorrectAnswers value="true" /><timeOfAnswer value="60" /><repeatWithoutAnswer value="false" /><showFinalInfo value="true" /></presentationParameters><htmlParameters><bgColor value="#ffffff" /><background value="" /><titleColor value="#000066" /></htmlParameters><evaluationParameters><incorrectAnswer value="2" penalize="true" /><withoutAnswer value="0" penalize="false" /><knowledgePercentage value="100" /></evaluationParameters></runningParameters><irtParameters><start initialProficiency="0.5" /><continuation irtModel="3" /><stop value="standardError" standardError="0.33" /></irtParameters></parameters></testFile>

=== ngphloc/zebra/runtime/wow/xmlroot/items/tutorial/test/testtutorial_tutorial_C_activity.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE testFile SYSTEM "../../testFile.dtd">
<testFile totalQuestion="3" lastUse="9/11/2004" fileName="testtutorial_tutorial_C_activity.xml" name="testtutorial evaluation Test" course="tutorial" type="activity" execution="classic" path="tutorial/test/testtutorial_tutorial_C_activity.xml" enable="true"><concepts><concept value="tutorial.testtutorial" /></concepts><questions numberOfFiles="1"><questionsFile numberOfQuestions="3" path="tutorial/itemsFiles/testtutorial_tutorial_items.xml" concept="tutorial.testtutorial"><question codeQuestion="3" /><question codeQuestion="2" /><question codeQuestion="1" /></questionsFile></questions><parameters><runningParameters><presentationParameters><showInitialInfo value="true" /><questionsOrder value="RANDOM" /><answersOrder value="RANDOM" /><showQuestionCorrection value="true" /><verbose value="true" /><showCorrectAnswers value="true" /><timeOfAnswer value="60" /><repeatWithoutAnswer value="false" /><showFinalInfo value="true" /></presentationParameters><htmlParameters><bgColor value="#FFFFFF" /><background value="" /><titleColor value="#000000" /></htmlParameters><evaluationParameters><incorrectAnswer value="0" penalize="false" /><withoutAnswer value="0" penalize="false" /><knowledgePercentage value="100" /></evaluationParameters></runningParameters></parameters></testFile>
