=== ngphloc/zebra/runtime/wow/author/authorfiles/generatelist4.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT conceptList (name, concept*)>
<!ELEMENT concept (name, description?, resource?, nocommit?, stable?, stable_expr?, concepttype, title, hierarchy?, attribute+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT requirement (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT resource (#PCDATA)>
<!ELEMENT nocommit (#PCDATA)>
<!ELEMENT attribute (description?, default?, stable?, stable_expr?, casegroup?, generateListItem*)>
<!ATTLIST attribute name CDATA #REQUIRED
	type (string | int | bool) #REQUIRED
	isChangeable (true | false) "false"
	isPersistent (true | false) "true"
	isSystem (true | false) "false"	
>
<!ELEMENT stable (#PCDATA)>
<!ELEMENT stable_expr (#PCDATA)>
<!ELEMENT casegroup (defaultfragment, casevalue*)>
<!ELEMENT casevalue (value,returnfragment)>
<!ELEMENT defaultfragment (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT returnfragment (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT generateListItem (requirement, trueActions, falseActions?)>
<!ATTLIST generateListItem isPropagating (true | false) "true"> 
<!ELEMENT trueActions (action+)>
<!ELEMENT falseActions (action+)>
<!ELEMENT action (conceptName, attributeName, expression)>
<!ELEMENT conceptName (#PCDATA)>
<!ELEMENT attributeName (#PCDATA)>
<!ELEMENT expression (#PCDATA)>

<!ELEMENT hierarchy (firstchild, nextsib, parent)>
<!ELEMENT firstchild (#PCDATA)>
<!ELEMENT nextsib (#PCDATA)>
<!ELEMENT parent (#PCDATA)>
<!ELEMENT concepttype (#PCDATA)>
<!ELEMENT title (#PCDATA)>

=== ngphloc/zebra/runtime/wow/author/authorfiles/defaultConcept.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE concept SYSTEM "generatelist4.dtd"> 
  <concept>
    <name>defaultname</name>
    <description></description>
    <resource>file:/defaultname.xhtml</resource>
    <concepttype>page</concepttype>
    <title>defaultname</title>
    <attribute name="access" type="bool" isPersistent="false" isSystem="true" isChangeable="false">
      <description></description>
      <default></default>
      <generateListItem isPropagating="true">
	<requirement>true</requirement>
	<trueActions>
	  <action>
	    <conceptName>defaultname</conceptName>
	    <attributeName>knowledge</attributeName>
	    <expression>100</expression>
	  </action>
	  <action>
	    <conceptName>defaultname</conceptName>
	    <attributeName>visited</attributeName>
	    <expression>100</expression>
	  </action>
	</trueActions>
	<falseActions>
	  <action>
	    <conceptName>defaultname</conceptName>
	    <attributeName>knowledge</attributeName>
	    <expression>35</expression>
	  </action>
	</falseActions>
      </generateListItem>
    </attribute>
    <attribute name="knowledge" type="int" isPersistent="true" isSystem="false" isChangeable="false">
      <description></description>
      <default></default>
    </attribute>
    <attribute name="visited" type="int" isPersistent="true" isSystem="false" isChangeable="false">
      <description></description>
      <default></default>
    </attribute>
    <attribute name="suitability" type="int" isPersistent="false" isSystem="false" isChangeable="false">
      <description></description>
      <default>100</default>
    </attribute>
  </concept>
